### PR TITLE
🐪 updated to 1.7 argocd 🐪

### PR DESCRIPTION
**Pull request by eformat**
update to latest argocd and prom versions

### CODE REVIEW

**Comment by eformat** [comment]
May need to hold off on this as the new gpg feature in 1.7 breaks OCP deployment by operator

https://github.com/argoproj-labs/argocd-operator/issues/148

**Comment by garethahealy** [comment]
@eformat marked as WIP due to https://github.com/redhat-cop/helm-charts/pull/90#issuecomment-683368876

**Comment by springdo** [comment]
@eformat  - any update on this puppy?

**Comment by eformat** [comment]
@springdo - yay, once this rolls out to oepratorhub.io  we should be good to go, i will restest this 

https://github.com/argoproj-labs/argocd-operator/releases/tag/v0.0.14

in conjunction with

https://github.com/rht-labs/ubiquitous-journey/pull/184

**Comment by eformat** [comment]
@springdo @ckavili @garethahealy - this LGTM, tests ok on OCP4.5 now. please merge. cheers

**Pull request merged**
