### PR TITLE
Make Ansible Automation Platform chart modular

### PR DESCRIPTION
**Pull request by jfilipcz**
#### What is this PR About?
Remove the OperatorGroup and Subscription Template from chart in favor of using helm chart designed for the purpose as a dependency

#### How do we test this?
Run the chart ;) 

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Review by springdo — APPROVED** [review]
GTM

**Comment by springdo** [comment]
Im good with this change Kuba, just looks like the CI is failing for some reason

**Comment by jfilipcz** [comment]
Yeah, and I'm trying to work out why it fails:) Helm chart renders correctly

**Comment by eformat** [comment]
> Yeah, and I'm trying to work out why it fails:) Helm chart renders correctly

hey  @jfilipcz - did you get any further with the conf- test failing ? cheers

**Comment by jfilipcz** [comment]
Yeah, should be solved by https://github.com/redhat-cop/bats-library/pull/36

**Comment by jfilipcz** [comment]
Or not, there seems to be other test problem with the fact we're using sub-chart

**Comment by jfilipcz** [comment]
@eformat , tests were fixed, so the thing is ready to be merged

**Pull request merged**
