### PR TITLE
Helm chart for upstream Keycloak Operator and instance.

### PR DESCRIPTION
**Pull request by jtudelag**

### CODE REVIEW

**Comment by jtudelag** [comment]
So it is currently failing due to the maintainers....not sure how to digest that.

**Comment by jtudelag** [comment]
Issue upstream,  https://github.com/helm/chart-testing/issues/192. My question is. How the hell ct compares repo maintainers?

**Comment by jtudelag** [comment]
Leaving aside that I'm starting to hate `ct` ,we should think the right approach here.

**Comment by jtudelag** [comment]
Addressing also https://github.com/rht-labs/ubiquitous-journey/issues/5

**Comment by jtudelag** [comment]
Also https://github.com/rht-labs/ubiquitous-journey/issues/128

**Comment by eformat** [comment]
> Leaving aside that I'm starting to hate `ct` ,we should think the right approach here.

Hi @jtudelag - OK .. the ct lint fails .. cause your maintainer handle has to match user id in github, missing 'g', change Chart.yaml to:

- name: jtudelag

and ct lint will work

ct lint --debug --target-branch=jtudelag-keycloak-operator --charts=charts/keycloak-operator

**Comment by jtudelag** [comment]
> > Leaving aside that I'm starting to hate `ct` ,we should think the right approach here.
> 
> Hi @jtudelag - OK .. the ct lint fails .. cause your maintainer handle has to match user id in github, missing 'g', change Chart.yaml to:
> 
>     * name: jtudelag
> 
> 
> and ct lint will work
> 
> ct lint --debug --target-branch=jtudelag-keycloak-operator --charts=charts/keycloak-operator

Pff....thanks @eformat for the hint! I was going insane with `ct`, still dont like it ;).

**Comment by jtudelag** [comment]
Squashed commits, fixed the maintainer name typo...

**Review by garethahealy — CHANGES_REQUESTED** [review]
can a conftest be added before merging please:
- https://github.com/redhat-cop/helm-charts/blob/master/_test/conftest.sh

**Pull request closed without merging**
