### PR TITLE
Make stackrox chart modular

### PR DESCRIPTION
**Pull request by jfilipcz**
#### What is this PR About?
This PR moves the stackrox chart to use parameters-fed subscription instead of hardcode

#### How do we test this?
helm template ;)

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Comment by jfilipcz** [comment]
@springdo @ckavili @eformat  FYI ;)

**Comment by eformat** [comment]
H @jfilipcz .. not sure about this - as it introduces a dependency on the operatorhub chart which does not add much other than a layer of abstraction to apply the Subcription. Does it really make sense for a single app Chart to do this ? i get it when we have many operators .. but not one.

**Comment by jfilipcz** [comment]
Hey @eformat, on technical level, it doesn't really matter how we do that, I've decided to go with the sub-chart to keep the approach consistent with other charts in this repo

**Comment by eformat** [comment]
> Hey @eformat, on technical level, it doesn't really matter how we do that, I've decided to go with the sub-chart to keep the approach consistent with other charts in this repo

that is the point though. charts in this repo with a single Subscription - are not tied to a dependency on the operatorhub chart.
this PR changes that. personally i'd prefer we left the usage of operatorhub chart to higher level automation (e.g as we do in enablement-framework) rather than forcing this dep.

**Comment by eformat** [comment]
LGTM ! thanks @jfilipcz

**Pull request merged**
