### PR TITLE
Disable route when install to kubernetes

### PR DESCRIPTION
**Pull request by patsevanton**
I don`t use Openshift. And i dont know how install your chart in Openshift.
```
helm install --set route.enabled=false $NAME redhat-cop/$CHART_NAME
```
This line only for install to Kubernetes.

#### What is this PR About?
Describe the contents of the PR

#### How do we test this?
Provide commands/steps to test this PR.

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Comment by springdo** [comment]
hi @patsevanton  - thanks for your contribution! 

This repo is a collection of charts for use on Red Hat OpenShift hence the use of `route` defaulted to `true`. As a suggestion, to make things more pure kubernetes friendly, why don't we add another line in the `README` underneath with your suggestion. This way the default values are honoured as per the the instruction.

**Comment by patsevanton** [comment]
May write
Install to k8s:
```bash
helm install --set route.enabled=false $NAME redhat-cop/$CHART_NAME
eg:
helm install --set route.enabled=false my-jenkins redhat-cop/jenkins
```

Install to Openshift:
```bash
helm install $NAME redhat-cop/$CHART_NAME
eg:
helm install my-jenkins redhat-cop/jenkins
```

I dont check install to Openshift

**Comment by springdo** [comment]
Yup - sounds good to me! Thanks @patsevanton

**Comment by garethahealy** [comment]
@patsevanton ; you able to update the PR with the suggested changes?

**Comment by patsevanton** [comment]
Hello. I dont understand where i need rewrite/refactore code

**Comment by garethahealy** [comment]
It's in reference to this comment:
- https://github.com/redhat-cop/helm-charts/pull/198#issuecomment-932124595

The current commits don't show this.

**Comment by patsevanton** [comment]
I am sorry. Busy.

**Pull request closed without merging**
