### PR TITLE
🕵️‍♀️ ADD - SealedSecrets helper chart discussed in meetup 👀

### PR DESCRIPTION
**Pull request by springdo**
@tylerauerbeck / @ckavili / @eformat  - this is the chart we said would be useful in the 🦄🔥 meetup we had some weeks back. Have a look and a play. Chart can be used in 2 ways:
1) as a dependency of another chart 
2) as a centrally managed chart for all secrets. 

If you want to overwrite other app secrets, they need to be edited to include an [annotation as shown here](https://github.com/bitnami-labs/sealed-secrets#managing-existing-secrets) 

```
sealedsecrets.bitnami.com/managed: "true"
```

### CODE REVIEW

**Comment by ckavili** [comment]
Do we have any other helpers in mind? Asking for the folder structure 😅

```
helpers
    └── sealed-secrets
        ├── Chart.yaml
        ├── README.md
        ├── templates
        └── valus.yaml
```

**Comment by springdo** [comment]
heyyyy @ckavili ! Yeah I think we did have a plan for others, like ones for the `ServiceMonitor` or what ever it's called now? Are there others?

**Comment by ckavili** [comment]
`ServiceMonitor` yes! I was trying to remember it while writing that comment 😅 but honestly, I don't have anything else in my mind at the moment 🤔

**Comment by springdo** [comment]
Hey @ckavili! Yeah we could have more helpers, but im not too sure a folder structure such as this will work with the releaser gh-action for the charts? I'd have to test it out.  I think it's cleaner to have separate charts for each of the helpers though for sure!

**Comment by ckavili** [comment]
yeah, I was thinking combine different charts folders under `charts/helpers` directory but let's see if we are going to have many of those..LGTM  👍

**Pull request merged**
