### PR TITLE
added more .test.sh scripts for charts

### PR DESCRIPTION
**Pull request by garethahealy**
#### What is this PR About?
added more scripts to install/test/cleanup charts on an OCP cluster

#### How do we test this?
run `_test/prow.sh` against a cluster

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Comment by garethahealy** [comment]
CI has failed as it wants the chart versions bumped. nothing in the charts has actually changed, just a new file in the dir. 

bump or not? thoughts @eformat @springdo @ckavili ?

**Comment by ckavili** [comment]
I think no need to bump since it won't be mixed with helm's test approach but I was wondering what you (and the others) think to have [chart tests](https://helm.sh/docs/topics/chart_tests/) and run `helm test..` as check with Prow only for the updated charts as we have in lint or release step?

**Comment by garethahealy** [comment]
@ckavili ; i think putting helm tests into the charts is a good idea. simplifies the testing for each chart.

looks like argocd doesn't support the hook (https://argoproj.github.io/argo-cd/user-guide/helm/).

do you know if the charts would need to be "installed" differently, i.e.: template vs install - does test work for both?

**Comment by ckavili** [comment]
`helm test` only runs against a chart installed with `helm install..` and test hook is only valid through a helm test command. (as far as I know) when you install a chart through Argo CD, it won't create the object that has ` "helm.sh/hook": test` annotation.
and `helm template .. | oc apply -f-` is not helpful in this case as it creates the test object at the same time as application objects so it usually fails 🤷

**Comment by jtudelag** [comment]
I came across this repo, might be useful...https://github.com/redhat-certification/chart-verifier

**Comment by garethahealy** [comment]
@ckavili ; good to merge? or need anything changed?

**Comment by ckavili** [comment]
one last thing 😅 would you also like to add `--skip-tests` parameter for `helm template..` ones? ..when we have helm tests (https://github.com/redhat-cop/helm-charts/issues/143) and also keep testing charts with `helm template` for Argo CD approach (https://github.com/redhat-cop/helm-charts/issues/138), I think there is no need to run tests there since the hook won't be honored with template command 😁

**Comment by garethahealy** [comment]
@ckavili ; pushed.

**Pull request merged**
