### PR TITLE
🦈 plogios wrapper helm chart 🦈

### PR DESCRIPTION
**Pull request by eformat**
Add a small wrapper helm chart for the TSSC/Plogios platform.

This chart installs the plogios platform into your openshift cluster at namespace scope (for now) which causes less havoc. Can add in cluster deployment support when it settles down upstream a bit.

See here for plogios doco - https://github.com/ploigos/ploigos-software-factory-operator

Usage of this chart is in the README.md

### CODE REVIEW

**Comment by sabre1041** [comment]
@eformat Theres a race condition between when the Operator is able to roll out the CRD and when the Custom Resource is created

**Comment by eformat** [comment]
> @eformat Theres a race condition between when the Operator is able to roll out the CRD and when the Custom Resource is created

yeah, @sabre1041 have you seen a good pattern for this in helm3 ? in the past, when rolling out operators into a new cluster.. the options seem seem to be:

- deploy as separate part of the same chart using flags (subscription only for example)
- put the subscripton into the crd/ folder .. loose ability to use mustache templating which is a pain for namespaced subscriptions
- deploy as separate chart dep ..

i have seen attempts to use hooks in a single chart deploy .. but not a totally working solution .. happy to incorporate here if you have one !!

**Comment by dwinchell** [comment]
@eformat thank you!! - the Ploigos team

**Comment by eformat** [comment]
@sabre1041 @dwinchell 

i have reorganised this now .. into a ploigos chart and a ploigos subscriptions dependent chart

this allows the subscription to deploy, waits for the crd to be available before deploying the main chart

also added csv delete hooks, so helm delete works.

cheers

**Comment by eformat** [comment]
and @sabre1041 .. now simplified moving tsscplatform to post-install phase, single chart.

thx !!

**Review by sabre1041 — APPROVED** [review]
LGTM

**Pull request merged**
