### PR TITLE
Added test files which can be used by prow

### PR DESCRIPTION
**Pull request by garethahealy**
#### What does this PR do?
Attempting to bring this repo under CI/automated testing.

The general idea being:
- each dir would have a `.test.sh` script, which runs helm template, test and cleanup.
- there's a `_test/prow.sh` script which runs all of them. which would be hooked up to prow, in the future.

not all charts are tested, but 70% are. https://github.com/redhat-cop/helm-charts/issues/15

#### How should this be tested?
_test/prow.sh

### CODE REVIEW

**Comment by garethahealy** [comment]
@springdo @ckavili ; be good to get some feeedback/input on this to move it forward

**Comment by ckavili** [comment]
Sorry for the late reply. It seems like a good start for me! We can improve on top of this based on the apps, like if Jenkins agents are built also fine etc.

**Comment by eformat** [comment]
hi @garethahealy, @ckavili  - this has been sitting around for a while, looks like linting failed at the time ? still good to go ?

**Comment by garethahealy** [comment]
@eformat ; just done a rebase. not sure why linting would have been failing, no charts have been changed only 1 extra file has been added into a chart dir. does that require a version bump?

**Comment by garethahealy** [comment]
latest linting failure would suggest versions need a bump

**Comment by eformat** [comment]
LGTM

**Pull request merged**
