### PR TITLE
🐬 icon added for helm charts 🐬

### PR DESCRIPTION
**Pull request by ckavili**
Added icon for helm charts

Fixes https://github.com/redhat-cop/helm-charts/issues/102

### CODE REVIEW

**Comment by garethahealy** [comment]
@ckavili ; does the console resize these? some look quite large

**Comment by ckavili** [comment]
Yup, I checked all on UI, they seem fine :)
Screenshot 2021-01-29 at 12 34 04

**Comment by garethahealy** [comment]
cool - presume linting is failing due to version bump

**Comment by eformat** [comment]
LGTM

**Pull request merged**
