### PR TITLE
adding helper-operator, helper-status-checker and update-clusterversi…

### PR DESCRIPTION
**Pull request by tjungbauer**
adding helper-operator, helper-status-checker and update-clusterversion as a first test

#### What is this PR About?
Added some charts to see how well it is going (Merging charts.stderr.at to redhat-cop)

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Comment by ckavili** [comment]
hey @tjungbauer, many thanks for the PR! 🚀 I especially love the detailed documentation 🙌 I see that helper-operator and helper-status-checker have similar capabilities with the existing operators-installer chart [here](https://github.com/redhat-cop/helm-charts/tree/main/charts/operators-installer). Do you think we can merge these somehow? like bringing enabling console link bits into the existing chart for example 🤔

**Comment by tjungbauer** [comment]
Hi @ckavili I personally would keep it separated, since they have two different purposes and are also the base for the operators I am trying to PR :)

**Comment by ckavili** [comment]
I wouldn't mind, to be honest..I'm more on the side of maintaining only one chart to deploy operators..but also I just realized we still have this [operatorhub chart](https://github.com/redhat-cop/helm-charts/tree/main/charts/operatorhub) hanging out 😅 so we can have your helper-operator chart instead..but first, I'd like to ask for a second opinion @eformat  🙈

**Comment by tjungbauer** [comment]
sure, just keep in mind that any operator here (https://charts.stderr.at/) is using the helper-operator and helper-status-checker. 
I did not put everything into the PR ... I started small :)

**Comment by ckavili** [comment]
hey @tjungbauer , linter is complaining about either too many empty blank lines ( Error: 13:1 [empty-lines] too many blank lines (1 > 0)) or no empty lines. Would you mind to check those? then I'll smash the PR in 🚀  thanks a lot!

**Pull request merged**
